### ISSUE TITLE
How to build native-image

### ISSUE THREAD

**Issue by hAh0L13** [leviysoft/mockingbird#76]
**Version**: main

### Expected behavior

Documented, easy-to-reproduce way to build own native-image for mockingbird

### Actual behavior

No docs. Try to use [GraalVM JDK-22](https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-22.0.2/graalvm-community-jdk-22.0.2_linux-x64_bin.tar.gz) directly and try to use [native-image sbt plugin](https://github.com/scalameta/sbt-native-image) v0.3.4
Direct use of native-image binary isn't possible - which Class should I use? Or which jar should I use and so. 
Using plugin resolve this problems, but produce errors - 
```
Caused by: java.lang.IllegalStateException: Polyglot version compatibility check failed.
Your Java runtime '22.0.2+9-jvmci-b01' with native-image feature version '24.0.2' is incompatible with polyglot version '23.1.4'.
Update the org.graalvm.polyglot versions to at least '24.0.2' to resolve this.
```
When I bumped Polyglot version or ignore this error, another error occurs:
```
Caused by: java.lang.IllegalAccessError: superinterface check failed: class com.oracle.truffle.runtime.enterprise.EnterpriseTruffleTypes (in unnamed module @0x1af05b03) cannot access class com.oracle.truffle.runtime.TruffleTypes (in module org.graalvm.truffle.runtime) because module org.graalvm.truffle.runtime does not export com.oracle.truffle.runtime to unnamed module @0x1af05b03
```

Can you provide some docs about building native-image?

@mockingbird/maintainers

**Comment by danslapman** [comment]
Hi @hAh0L13!

I didn't tried GraalVM JDK-22 yet, mockingbird is currently build with JDK-21.
As for the question - there's a guide for building mockingbird on a local machine, here it is: https://github.com/leviysoft/mockingbird/wiki/Local-backend-development#running-mockinbird-as-a-native-image

**Comment by danslapman** [comment]
Closing since docs does exist. Feel free to ask if there will be more questions
